import pyautogui,keyboard,time,os

def ctrl_z():
    pyautogui.keyDown('ctrl')
    pyautogui.keyDown('z')
def flow():
    ctrl_z()
    pyautogui.click(232,967)
    ctrl_z()
    pyautogui.click(155,1001)
    ctrl_z()
    pyautogui.click(171,887)
    ctrl_z()
    pyautogui.click(70,973)
    ctrl_z()
    pyautogui.click(72,882)
def initialize():
    pyautogui.keyUp('ctrl')
    pyautogui.keyUp('z')
def open():
    pyautogui.click(225,957)
    pyautogui.click(2075,676)
    time.sleep(70)
def close():
    time.sleep(20)
    pyautogui.click(964,674)
    pyautogui.click(2609,478)
    time.sleep(10)
    pyautogui.click(2609,478)
    pyautogui.keyDown('esc')
    pyautogui.keyUp('esc')
    pyautogui.click(964,674)
    pyautogui.keyDown('esc')
    pyautogui.keyUp('esc')
    time.sleep(2)
a = 1
pyautogui.PAUSE = 0.01
while a == 1:
    keyboard.wait(']')
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    initialize()