import pyautogui,keyboard,time,os
def ctrl_z():
    pyautogui.PAUSE = 0.01
    pyautogui.keyDown('ctrl')
    pyautogui.keyDown('z')
def flow():
    pyautogui.PAUSE = 0.01
    ctrl_z()
    pyautogui.click(232,967)
    ctrl_z()
    pyautogui.click(155,1001)
    ctrl_z()
    pyautogui.click(171,887)
    ctrl_z()
    pyautogui.click(70,973)
    ctrl_z()
    pyautogui.click(72,882)
def initialize():
    pyautogui.keyUp('ctrl')
    pyautogui.keyUp('z')
def open():
    pyautogui.click(250,950)
    pyautogui.hotkey('alt','tab')
    pyautogui.click(250,950)
    pyautogui.hotkey('alt','tab')
def close():
    pyautogui.PAUSE = 1
    time.sleep(25)
    pyautogui.click(964,674)
    pyautogui.hotkey('alt', 'tab')
    pyautogui.click(964,674)
    time.sleep(15)
    pyautogui.hotkey('esc')
    pyautogui.hotkey('alt', 'tab')
    pyautogui.hotkey('esc')
    pyautogui.click(346,860)
    pyautogui.hotkey('alt', 'tab')
    pyautogui.click(346,860)
    pyautogui.hotkey('alt', 'tab')
a = 1
pyautogui.PAUSE = 1
time.sleep(3)
while a == 1:
    open()
    time.sleep(90)
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    flow()
    initialize()
    close()